[package]
name = "heim-runtime"
version = "0.0.4"
authors = ["svartalf <self@svartalf.info>"]
edition = "2018"
description = "Runtime shims for heim crate"
keywords = ["heim", "runtime", "shim", "sync"]
categories = ["asynchronous", "os", "api-bindings"]
repository = "https://github.com/heim-rs/heim"
license = "Apache-2.0 OR MIT"

[dependencies]
cfg-if = "0.1.10"
futures-util-preview = "0.3.0-alpha.19"

# `runtime-polyfill` feature dependencies
lazy_static = { version = "1.4.0", optional = true }
futures-channel-preview = { version = "0.3.0-alpha.19", optional = true }
futures-executor-preview = { version = "0.3.0-alpha.19", optional = true }

[dev-dependencies]
version-sync = "0.8"

[features]
default = ["runtime-polyfill"]
runtime-async-std = []
runtime-tokio = []
runtime-polyfill = ["lazy_static", "futures-channel-preview", "futures-executor-preview"]
