[package]
name = "heim-runtime"
version = "0.0.4"
authors = ["svartalf <self@svartalf.info>"]
edition = "2018"
description = "Runtime shims for heim crate"
keywords = ["heim", "runtime", "shim", "sync"]
categories = ["asynchronous", "os", "api-bindings"]
repository = "https://github.com/heim-rs/heim"
license = "Apache-2.0 OR MIT"

[dependencies]
cfg-if = "0.1.10"
futures-util-preview = "0.3.0-alpha.19"

# `runtime-tokio` feature dependencies
tokio = { version = "0.2.0-alpha.6", optional = true, default-features = false, features = ["fs", "io"] }
tokio-fs = { version = "0.2.0-alpha.6", optional = true }

# `runtime-async-std` feature dependencies
async-std = { version = "^0.99", optional = true }

[dev-dependencies]
version-sync = "0.8"

[features]
default = ["runtime-async-std"]
runtime-tokio = ["tokio", "tokio-fs"]
runtime-async-std = ["async-std"]
